"""Universal Studio Master HUD Generator for Moho 14 Production Rigs.

Automatically builds a standardized, aesthetic, on-screen HUD Control Box
for ANY character rig generated by the MCP server.

Guarantees:
1. Clean docked panel layout on the side of the canvas (Right at x = +0.95).
2. Categorized sections (Head & Face, Hands & Gestures, Dynamics & FX).
3. Arc gauges with calibrated tick marks and state text for every dial.
4. Moho Smart Dial bones with `bone_label_showing: True` positioned over each gauge.
5. Fully automated integration across procedural rigs, PSD imports, and artwork compilers.
"""
from __future__ import annotations

import math
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PIL import Image, ImageDraw, ImageFont

from ..pir.schema import Bone, Channel, Part
from .modules import wire_dial, BASE_INTERP


@dataclass
class DialDefinition:
    id: str                         # Bone ID (e.g. "🎭 Expressions / Lipsync")
    label: str                      # Display label in HUD
    section: str                    # Section name ("HEAD & FACE", "HANDS & GESTURES", "DYNAMICS & FX")
    min_angle_deg: float            # e.g. -60
    max_angle_deg: float            # e.g. 60
    states: List[str]               # e.g. ["Rest", "A", "E", "O", "MBP", "L"]
    target_switch: Optional[Part]   # Target Switch Part to wire to
    default_state: str = ""


class StudioHUDGenerator:
    """Generates standardized, professional HUD Control Boards for Moho rigs."""

    SECTION_THEMES = {
        "dark_gold": {
            "bg": (24, 20, 42, 240),
            "border": (235, 179, 56, 255),
            "header_bg": (38, 28, 72, 250),
            "header_text": (253, 243, 207),
            "sec_bg": (34, 26, 60, 210),
            "sec_border": (140, 110, 190, 150),
            "sec_title": (235, 179, 56),
            "gauge_arc": (235, 179, 56),
            "text_primary": (240, 230, 255),
            "text_secondary": (190, 180, 220),
        },
        "cyber_dark": {
            "bg": (18, 22, 32, 240),
            "border": (64, 196, 255, 255),
            "header_bg": (24, 34, 52, 250),
            "header_text": (200, 240, 255),
            "sec_bg": (26, 36, 54, 210),
            "sec_border": (80, 140, 200, 150),
            "sec_title": (64, 196, 255),
            "gauge_arc": (64, 196, 255),
            "text_primary": (230, 245, 255),
            "text_secondary": (160, 190, 220),
        }
    }

    @classmethod
    def generate_hud_board(
        cls,
        character_name: str,
        dials: List[DialDefinition],
        output_image_path: str,
        theme_name: str = "dark_gold",
        board_w: int = 460,
        board_h: int = 680,
        dock_pos_x: float = 0.95,
        dock_pos_y: float = 0.0
    ) -> Tuple[Part, Bone, List[Bone]]:
        """Generates the HUD graphic plate and returns (HUD Part, HUD Root Bone, Dial Bones)."""
        theme = cls.SECTION_THEMES.get(theme_name, cls.SECTION_THEMES["dark_gold"])
        img_out = Path(output_image_path).resolve()
        img_out.parent.mkdir(parents=True, exist_ok=True)

        hud_img = Image.new("RGBA", (board_w, board_h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(hud_img)

        # 1. Background Box
        draw.rounded_rectangle([8, 8, board_w - 8, board_h - 8], radius=18, fill=theme["bg"], outline=theme["border"], width=3)
        draw.rounded_rectangle([14, 14, board_w - 14, board_h - 14], radius=14, outline=theme["sec_border"], width=1)

        # 2. Header
        draw.rectangle([8, 8, board_w - 8, 60], fill=theme["header_bg"])
        draw.text((board_w // 2, 34), f"{character_name.upper()} · MASTER RIG CONTROLS", fill=theme["header_text"], anchor="mm")

        # 3. Group dials by section
        sections: Dict[str, List[DialDefinition]] = {}
        for d in dials:
            sections.setdefault(d.section, []).append(d)

        sec_keys = list(sections.keys())
        total_secs = len(sec_keys) or 1
        available_h = board_h - 80 - 15
        sec_h = max(160, (available_h // total_secs) - 10)

        dial_bones: List[Bone] = []
        hud_root_bone = Bone(
            id="HUD_Master_Controller",
            parent=None,
            position=(dock_pos_x, dock_pos_y),
            angle=math.radians(90),
            length=0.1,
            strength=0.0
        )

        curr_y = 75
        scale_x = 0.85 / board_w
        scale_y = 1.25 / board_h

        for sec_name, sec_dials in sections.items():
            draw.rounded_rectangle([20, curr_y, board_w - 20, curr_y + sec_h], radius=10, fill=theme["sec_bg"], outline=theme["sec_border"], width=1)
            draw.text((32, curr_y + 16), sec_name, fill=theme["sec_title"], anchor="lm")

            num_dials = len(sec_dials)
            for idx, dial in enumerate(sec_dials):
                if num_dials == 1:
                    cx = board_w // 2
                elif num_dials == 2:
                    cx = (board_w // 4) * (1 + 2 * idx)
                else:
                    cx = int(40 + (board_w - 80) * (idx + 0.5) / num_dials)

                cy = curr_y + (sec_h // 2) + 12
                r = 40

                draw.text((cx, cy - 38), dial.label, fill=theme["text_primary"], anchor="mm")
                draw.arc([cx - r, cy - r, cx + r, cy + r], start=dial.min_angle_deg, end=dial.max_angle_deg, fill=theme["gauge_arc"], width=2)

                states_summary = " · ".join(dial.states[:4])
                if len(dial.states) > 4:
                    states_summary += f" (+{len(dial.states)-4})"
                draw.text((cx, cy + r + 12), states_summary, fill=theme["text_secondary"], anchor="ms")

                # Moho bone coordinates relative to HUD_Master_Controller
                bx = (cx - (board_w / 2.0)) * scale_x
                by = ((board_h / 2.0) - cy) * scale_y

                # Create Smart Dial Bone
                bone = Bone(
                    id=dial.id,
                    parent="HUD_Master_Controller",
                    position=(round(bx, 4), round(by, 4)),
                    angle=math.radians(90),
                    length=0.18,
                    strength=0.0,
                    constraints=True,
                    min_constraint=math.radians(dial.min_angle_deg),
                    max_constraint=math.radians(dial.max_angle_deg),
                    is_dial=True,
                    extra_channels_raw={"bone_label_showing": True}
                )
                dial_bones.append(bone)

                if dial.target_switch:
                    span_angles = [
                        math.radians(dial.min_angle_deg + i * (dial.max_angle_deg - dial.min_angle_deg) / max(1, len(dial.states) - 1))
                        for i in range(len(dial.states))
                    ]
                    wire_dial(bone, dial.id, span_angles, dial.target_switch, dial.states)

            curr_y += sec_h + 10

        hud_img.save(str(img_out))
        print(f"Master HUD plate saved to: {img_out}")

        hud_part = Part(
            id="part_hud_master_board",
            name="🎛️ Master HUD Control Board",
            type="image",
            parent=None,
            bone="HUD_Master_Controller",
            image_ref=str(img_out),
            origin=(-dock_pos_x, -dock_pos_y),
            z_order=5
        )
        hud_part.transforms = {
            "translation": Channel(
                type="Vec3",
                when=[0],
                val=[(dock_pos_x, dock_pos_y, 0.0)],
                interp=[dict(BASE_INTERP)]
            )
        }

        return hud_part, hud_root_bone, dial_bones
