import fs from 'fs';import path from 'path';
import {FactoryAuth,FactoryFoundationStore} from '../src/adapters/factoryFoundation/index.js';

describe('Factory Phase 1 foundation',()=>{
 test('durable job survives store re-open and keeps DAG checkpoints',async()=>{const root=fs.mkdtempSync(path.join(process.cwd(),'output','factory-db-'));const a=new FactoryFoundationStore(root);const job=await a.createJob('scene',{scene:'s1'},['input','worker','verify']);await a.setStep(job.jobId,'input','completed',{sha:'abc'});await a.setJob(job.jobId,'running',.3);const b=new FactoryFoundationStore(root);const restored=await b.getJob(job.jobId);expect(restored.status).toBe('running');expect(restored.steps[0].checkpoint).toEqual({sha:'abc'});});
 test('content-addressed artifact is copied and hash verified',async()=>{const root=fs.mkdtempSync(path.join(process.cwd(),'output','factory-test-'));const file=path.join(root,'input.txt');fs.writeFileSync(file,'real artifact');const store=new FactoryFoundationStore(root);const first=await store.ingest(file,'text/plain'),second=await store.ingest(file,'text/plain');expect(first.sha256).toMatch(/^[a-f0-9]{64}$/);expect(first.storedPath).toBe(second.storedPath);expect(fs.readFileSync(first.storedPath,'utf8')).toBe('real artifact');});
 test('configured token enforces RBAC',()=>{const old=process.env.HARMONY_FACTORY_TOKENS;process.env.HARMONY_FACTORY_TOKENS=JSON.stringify({secret:{id:'artist-1',role:'artist'}});const auth=new FactoryAuth();expect(auth.authorize('secret','viewer').id).toBe('artist-1');expect(()=>auth.authorize('secret','pipeline_admin')).toThrow();expect(()=>auth.authorize('bad','viewer')).toThrow();if(old===undefined)delete process.env.HARMONY_FACTORY_TOKENS;else process.env.HARMONY_FACTORY_TOKENS=old;});
 test('cancel is persisted',async()=>{const root=fs.mkdtempSync(path.join(process.cwd(),'output','factory-cancel-')),store=new FactoryFoundationStore(root);const job=await store.createJob('scene',{},['one']);const cancelled=await store.cancel(job.jobId);expect(cancelled.status).toBe('cancelled');expect(cancelled.cancelRequested).toBe(true);});
});
