import { describe, it, expect } from '@jest/globals';

import {
  mohoPerformancePirSchema,
  MOHO_PERFORMANCE_PIR_SCHEMA_VERSION,
  type MohoPerformancePir,
  type MohoBoneKey,
  type MohoSwitchKey,
  type MohoSmartBoneActionKey
} from '../src/schemas/mohoPerformancePir.js';

import { emitMohoLua } from '../src/services/mohoLuaEmitter/index.js';

import type { MohoCommandPlan } from '../src/schemas/mohoCommandPlan.js';

function validMohoPerformancePir(): MohoPerformancePir {
  return {
    schemaVersion: MOHO_PERFORMANCE_PIR_SCHEMA_VERSION,
    performanceId: 'perf_main_v1',
    rigType: 'humanoid_2leg',
    shotManifestRef: 'show/shot_manifest.json',
    mohoShowBibleRef: 'show/moho_show_bible.json',
    boneKeys: [],
    switchKeys: [],
    smartBoneActions: [],
    cameraKeys: [],
    fxKeys: [],
    deterministicFingerprint: 'a'.repeat(64),
    provenance: {
      compiledAt: '2026-07-27T12:00:00Z',
      compilerVersion: 'moho-pir-compiler/1.0.0'
    }
  };
}

function makePlan(operations: MohoCommandPlan['operations']): MohoCommandPlan {
  return {
    schemaVersion: 'toon-boom-mcp/moho-command-plan-v1',
    planId: 'plan_smoke_performance_pir',
    documentPath: null,
    createdAt: '2026-07-27T12:00:00Z',
    status: 'implemented_unverified',
    requiresRealMoho: true,
    sourceManifestSha256: 'b'.repeat(64),
    operations,
    acceptanceGates: [
      'g1', 'g2', 'g3', 'g4', 'g5', 'g6'
    ],
    provenance: {
      compiler: 'MohoRigPlanCompiler v1',
      source: 'mohoPerformancePirSmoke.test'
    }
  };
}

describe('mohoPerformancePir Lua-emitter smoke (Sprint 1)', () => {
  it('SMOKE: PerformancePIR schema parses a humanoid 2leg fixture', () => {
    const fixture: MohoPerformancePir = {
      ...validMohoPerformancePir(),
      rigType: 'humanoid_2leg'
    };
    const result = mohoPerformancePirSchema.safeParse(fixture);
    expect(result.success).toBe(true);
  });

  it('SMOKE: boneKey for HEAD_ROT (rotation channel) flows through the Lua emitter', () => {
    const boneKey: MohoBoneKey = {
      boneId: 1,
      boneName: 'Head_Peg',
      channel: 'rotation',
      frame: 12,
      value: 15,
      interpolation: 'ease_in_out'
    };
    const fixture: MohoPerformancePir = {
      ...validMohoPerformancePir(),
      rigType: 'humanoid_2leg',
      boneKeys: [boneKey]
    };

    expect(mohoPerformancePirSchema.safeParse(fixture).success).toBe(true);

    const plan = makePlan([
      {
        commandId: 'mcmd_001',
        type: 'add_bone',
        params: { name: boneKey.boneName, x: 0, y: 0, lengthPx: 50, angleDeg: 0 },
        preconditions: ['bone_layer_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'add_bone_head_peg_001',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'bone', path: null, nonempty: true },
        verification: { method: 'bone_listed', required: true, acceptance: ['bone_count>=1'] }
      }
    ]);

    const lua = emitMohoLua(plan, 'Hero');

    expect(lua).toContain('-- Generated by MohoRigPlanCompiler v1');
    expect(lua).toContain('addBone("Head_Peg"');
    expect(lua).toContain('addBone("Head_Peg", 0, 0, 50, 0)');
    expect(lua).toContain('Hero_Skeleton');
  });

  it('SMOKE: boneKey for BODY_TRANSLATE (translation channel) serializes into expected Lua', () => {
    const boneKey: MohoBoneKey = {
      boneId: 2,
      boneName: 'Body_Peg',
      channel: 'translation',
      frame: 24,
      value: -5,
      interpolation: 'linear'
    };
    const fixture: MohoPerformancePir = {
      ...validMohoPerformancePir(),
      rigType: 'humanoid_2leg',
      boneKeys: [boneKey]
    };

    expect(mohoPerformancePirSchema.safeParse(fixture).success).toBe(true);

    const plan = makePlan([
      {
        commandId: 'mcmd_002',
        type: 'add_bone',
        params: { name: boneKey.boneName, x: 100, y: 200, lengthPx: 80, angleDeg: 0 },
        preconditions: ['bone_layer_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'add_bone_body_peg_002',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'bone', path: null, nonempty: true },
        verification: { method: 'bone_listed', required: true, acceptance: ['bone_count>=1'] }
      }
    ]);

    const lua = emitMohoLua(plan, 'Hero');

    expect(lua).toContain('addBone("Body_Peg", 100, 200, 80, 0)');
  });

  it('SMOKE: switchKey for mouth serializes into switch-layer + choice Lua', () => {
    const switchKey: MohoSwitchKey = {
      switchLayerName: 'Mouth_Switch',
      frame: 6,
      choice: 'open_mouth',
      interpolation: 'step'
    };
    const fixture: MohoPerformancePir = {
      ...validMohoPerformancePir(),
      rigType: 'humanoid_2leg',
      switchKeys: [switchKey]
    };

    expect(mohoPerformancePirSchema.safeParse(fixture).success).toBe(true);

    const plan = makePlan([
      {
        commandId: 'mcmd_010',
        type: 'create_switch_layer',
        params: { layerName: switchKey.switchLayerName },
        preconditions: ['document_open'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'create_switch_layer_mouth_010',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'switch_layer', path: null, nonempty: true },
        verification: { method: 'layer_listed', required: true, acceptance: ['switch_layer_present'] }
      },
      {
        commandId: 'mcmd_011',
        type: 'add_switch_choice',
        params: { layerName: switchKey.switchLayerName, choiceName: switchKey.choice },
        preconditions: ['switch_layer_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'add_switch_choice_mouth_open_011',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'switch_choice', path: null, nonempty: true },
        verification: { method: 'choice_listed', required: true, acceptance: ['choice_present'] }
      }
    ]);

    const lua = emitMohoLua(plan, 'Hero');

    expect(lua).toContain('createSwitchLayer("Mouth_Switch")');
    expect(lua).toContain('addSwitchChoice("Mouth_Switch", "open_mouth")');
  });

  it('SMOKE: smartBoneAction serializes into create_smart_action + set_action_channel_key Lua', () => {
    const actionKey: MohoSmartBoneActionKey = {
      actionName: 'smile',
      targetBone: 'Mouth_SmartBone',
      frame: 10,
      angleDeg: 5.5,
      scaleX: 1,
      scaleY: 1
    };
    const fixture: MohoPerformancePir = {
      ...validMohoPerformancePir(),
      rigType: 'humanoid_2leg',
      smartBoneActions: [actionKey]
    };

    expect(mohoPerformancePirSchema.safeParse(fixture).success).toBe(true);

    const plan = makePlan([
      {
        commandId: 'mcmd_020',
        type: 'create_smart_action',
        params: { actionName: actionKey.actionName, targetBone: actionKey.targetBone },
        preconditions: ['smart_bone_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'create_smart_action_smile_020',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'smart_action', path: null, nonempty: true },
        verification: { method: 'action_listed', required: true, acceptance: ['action_present'] }
      },
      {
        commandId: 'mcmd_021',
        type: 'set_action_channel_key',
        params: {
          actionName: actionKey.actionName,
          boneName: actionKey.targetBone,
          frame: actionKey.frame,
          angleDeg: actionKey.angleDeg,
          scaleX: actionKey.scaleX,
          scaleY: actionKey.scaleY
        },
        preconditions: ['action_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'set_action_channel_key_smile_021',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'action_key', path: null, nonempty: true },
        verification: { method: 'key_listed', required: true, acceptance: ['key_present'] }
      }
    ]);

    const lua = emitMohoLua(plan, 'Hero');

    expect(lua).toContain('createSmartAction("smile", "Mouth_SmartBone")');
    expect(lua).toContain(
      'setActionChannelKey("smile", "Mouth_SmartBone", 10, 5.5, 1, 1)'
    );
  });

  it('SMOKE: full PerformancePIR shape (bone + switch + smartBoneAction) compiles to a single coherent Lua script', () => {
    const fixture: MohoPerformancePir = {
      ...validMohoPerformancePir(),
      rigType: 'humanoid_2leg',
      boneKeys: [
        {
          boneId: 1,
          boneName: 'Head_Peg',
          channel: 'rotation',
          frame: 12,
          value: 15,
          interpolation: 'ease_in_out'
        },
        {
          boneId: 2,
          boneName: 'Body_Peg',
          channel: 'translation',
          frame: 24,
          value: -5,
          interpolation: 'linear'
        }
      ],
      switchKeys: [
        {
          switchLayerName: 'Mouth_Switch',
          frame: 6,
          choice: 'open_mouth',
          interpolation: 'step'
        }
      ],
      smartBoneActions: [
        {
          actionName: 'smile',
          targetBone: 'Mouth_SmartBone',
          frame: 10,
          angleDeg: 5.5,
          scaleX: 1,
          scaleY: 1
        }
      ]
    };

    const parsed = mohoPerformancePirSchema.safeParse(fixture);
    expect(parsed.success).toBe(true);

    const plan = makePlan([
      {
        commandId: 'mcmd_100',
        type: 'add_bone',
        params: { name: 'Head_Peg', x: 0, y: 0, lengthPx: 50, angleDeg: 0 },
        preconditions: ['bone_layer_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'add_bone_head_peg_100',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'bone', path: null, nonempty: true },
        verification: { method: 'bone_listed', required: true, acceptance: ['bone_count>=1'] }
      },
      {
        commandId: 'mcmd_101',
        type: 'add_bone',
        params: { name: 'Body_Peg', x: 100, y: 200, lengthPx: 80, angleDeg: 0 },
        preconditions: ['bone_layer_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'add_bone_body_peg_101',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'bone', path: null, nonempty: true },
        verification: { method: 'bone_listed', required: true, acceptance: ['bone_count>=2'] }
      },
      {
        commandId: 'mcmd_110',
        type: 'create_switch_layer',
        params: { layerName: 'Mouth_Switch' },
        preconditions: ['document_open'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'create_switch_layer_mouth_110',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'switch_layer', path: null, nonempty: true },
        verification: { method: 'layer_listed', required: true, acceptance: ['switch_layer_present'] }
      },
      {
        commandId: 'mcmd_111',
        type: 'add_switch_choice',
        params: { layerName: 'Mouth_Switch', choiceName: 'open_mouth' },
        preconditions: ['switch_layer_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'add_switch_choice_mouth_open_111',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'switch_choice', path: null, nonempty: true },
        verification: { method: 'choice_listed', required: true, acceptance: ['choice_present'] }
      },
      {
        commandId: 'mcmd_120',
        type: 'create_smart_action',
        params: { actionName: 'smile', targetBone: 'Mouth_SmartBone' },
        preconditions: ['smart_bone_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'create_smart_action_smile_120',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'smart_action', path: null, nonempty: true },
        verification: { method: 'action_listed', required: true, acceptance: ['action_present'] }
      },
      {
        commandId: 'mcmd_121',
        type: 'set_action_channel_key',
        params: {
          actionName: 'smile',
          boneName: 'Mouth_SmartBone',
          frame: 10,
          angleDeg: 5.5,
          scaleX: 1,
          scaleY: 1
        },
        preconditions: ['action_exists'],
        destructiveLevel: 'reversible',
        idempotencyKey: 'set_action_channel_key_smile_121',
        rollback: { strategy: 'delete_created', snapshotRequired: false },
        expectedArtifact: { kind: 'action_key', path: null, nonempty: true },
        verification: { method: 'key_listed', required: true, acceptance: ['key_present'] }
      }
    ]);

    const lua = emitMohoLua(plan, 'Hero');

    expect(lua).toContain('-- Generated by MohoRigPlanCompiler v1');
    expect(lua).toContain('addBone("Head_Peg", 0, 0, 50, 0)');
    expect(lua).toContain('addBone("Body_Peg", 100, 200, 80, 0)');
    expect(lua).toContain('createSwitchLayer("Mouth_Switch")');
    expect(lua).toContain('addSwitchChoice("Mouth_Switch", "open_mouth")');
    expect(lua).toContain('createSmartAction("smile", "Mouth_SmartBone")');
    expect(lua).toContain(
      'setActionChannelKey("smile", "Mouth_SmartBone", 10, 5.5, 1, 1)'
    );
    expect(lua).toContain('[SUMMARY]');
    expect(lua).toContain('plan_smoke_performance_pir');
  });
});