import fs from 'fs';
import os from 'os';
import path from 'path';
import { SceneUnderstandingEngine } from '../src/adapters/sceneUnderstanding/index.js';
import { VoicePerformanceAnalyzer } from '../src/adapters/voicePerformanceAnalyzer/index.js';
import { PerformanceGenerator, ALL_PERFORMANCE_STYLES } from '../src/adapters/performanceGenerator/index.js';
import { VoicePerformanceReportBuilder } from '../src/adapters/voicePerformanceReport/index.js';
import { voiceAnalysisSchema, performancePlanSchema, performanceVariantSetSchema } from '../src/schemas/voicePerformance.js';

function scene(){return new SceneUnderstandingEngine().analyze({script:'Masha: Ты всё знал?\nIvan: Я… ничего не знал.\nMasha: Не лги!',sceneId:'voice_demo',sceneName:'Voice demo',fps:24,durationSeconds:6,characters:[{name:'Masha',role:'protagonist'},{name:'Ivan',role:'antagonist'}],dialogue:[{speaker:'Masha',text:'Ты всё знал?',startSec:.2,endSec:1.8},{speaker:'Ivan',text:'Я… ничего не знал.',startSec:2.1,endSec:4},{speaker:'Masha',text:'Не лги!',startSec:4.5,endSec:5.8}]});}
function wavFile(){const rate=8000,duration=2,samples=rate*duration,data=Buffer.alloc(samples*2);for(let i=0;i<samples;i++){const t=i/rate;const active=(t>.1&&t<.75)||(t>1.05&&t<1.85);const value=active?Math.sin(2*Math.PI*(t<1?180:240)*t)*.45:0;data.writeInt16LE(Math.round(value*32767),i*2);}const b=Buffer.alloc(44+data.length);b.write('RIFF',0);b.writeUInt32LE(36+data.length,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(data.length,40);data.copy(b,44);const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'voice-perf-')),'voice.wav');fs.writeFileSync(file,b);return file;}

describe('VoicePerformanceAnalyzer',()=>{
  test('analyzes a real PCM WAV and detects its silent gap',()=>{const a=new VoicePerformanceAnalyzer().analyze({audioPath:wavFile(),transcript:'Ты всё знал? Не лги!',speaker:'masha'});expect(voiceAnalysisSchema.safeParse(a).success).toBe(true);expect(a.audioAvailable).toBe(true);expect(a.sampleRate).toBe(8000);expect(a.durationSeconds).toBeCloseTo(2,2);expect(a.loudness.length).toBeGreaterThan(20);expect(a.pitchContour.length).toBeGreaterThan(2);expect(a.pauses.some(p=>p.duration>.15)).toBe(true);expect(a.provenance.emotionIsProxy).toBe(true);});
  test('works without audio and states duration-proportional limitation',()=>{const a=new VoicePerformanceAnalyzer().analyze({transcript:'Спокойно. Я всё понял.',durationSeconds:3});expect(a.audioAvailable).toBe(false);expect(a.words.length).toBe(4);expect(a.provenance.alignment).toBe('duration_proportional');expect(a.assumptions.join(' ')).toContain('Аудио не дано');});
  test('word and phoneme times are monotonic and bounded',()=>{const a=new VoicePerformanceAnalyzer().analyze({transcript:'Раз два три!',durationSeconds:2});for(const w of a.words){expect(w.endTime).toBeGreaterThan(w.startTime);expect(w.endTime).toBeLessThanOrEqual(2);}expect(a.phonemes.length).toBeGreaterThanOrEqual(a.words.length);});
});

describe('PerformanceGenerator',()=>{
  const voice=()=>new VoicePerformanceAnalyzer().analyze({transcript:'Ты всё знал? Я ничего не знал. Не лги!',durationSeconds:6,speaker:'masha'});
  test('has all seven required performance styles',()=>{expect(ALL_PERFORMANCE_STYLES).toEqual(expect.arrayContaining(['restrained','energetic','sarcastic','anxious','aggressive','comedic','custom']));});
  test('generates three distinct valid variants',()=>{const set=new PerformanceGenerator().generateVariants(scene(),voice(),'masha',3);expect(performanceVariantSetSchema.safeParse(set).success).toBe(true);expect(set.variants.map(v=>v.style)).toEqual(['restrained','energetic','sarcastic']);for(const p of set.variants){expect(performancePlanSchema.safeParse(p).success).toBe(true);expect(p.events.some(e=>e.kind==='gaze')).toBe(true);expect(p.events.some(e=>e.kind==='facial_expression')).toBe(true);}});
  test('styles create materially different event policies',()=>{const g=new PerformanceGenerator(),s=scene(),v=voice();const restrained=g.generate(s,v,'masha','restrained'),anxious=g.generate(s,v,'masha','anxious'),comedic=g.generate(s,v,'masha','comedic');expect(anxious.events.filter(e=>e.kind==='blink').length).toBeGreaterThan(restrained.events.filter(e=>e.kind==='blink').length);expect(comedic.events.some(e=>e.kind==='hold')).toBe(true);});
  test('mix takes gestures and poses from requested variants',()=>{const g=new PerformanceGenerator(),set=g.generateVariants(scene(),voice(),'masha',3);const mixed=g.mix(set.variants[0],set.variants[1],set.variants[2]);expect(performancePlanSchema.safeParse(mixed).success).toBe(true);expect(mixed.style).toBe('custom');expect(mixed.events.filter(e=>e.kind==='gesture').length).toBe(set.variants[1].events.filter(e=>e.kind==='gesture').length);expect(mixed.events.filter(e=>e.kind==='pose').length).toBe(set.variants[2].events.filter(e=>e.kind==='pose').length);});
  test('rejects unknown character',()=>{expect(()=>new PerformanceGenerator().generate(scene(),voice(),'ghost','restrained')).toThrow('не найден');});
  test('writes a self-contained HTML report',()=>{const set=new PerformanceGenerator().generateVariants(scene(),voice(),'masha',3);const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'perf-report-')),'report.html');new VoicePerformanceReportBuilder().buildToFile(set,file);const html=fs.readFileSync(file,'utf8');expect(html).toContain('<!doctype html>');expect(html).toContain('Эмоция — только предположение');expect(html).toContain('restrained');});
});
