import type { MohoCommandPlan } from '../../schemas/mohoCommandPlan.js';

/**
 * MohoLuaEmitter — turns a MohoCommandPlan into ONE deterministic Lua script
 * that builds the rig inside Moho Pro (Scripting > Run Lua Script).
 *
 * Fully supports:
 *   - 360 Turnaround & Switch layers
 *   - Vitruvian bone groups & alternative branches
 *   - Smart Bone actions & joint flexion corrections
 *   - Constraints (angle, scale, position)
 *   - Delaunay Smart Warp meshes
 *   - Smart projected shadows
 *   - Animator contract (shy bones, color coding)
 */

function luaStr(s: string): string {
  return JSON.stringify(s);
}

function emitOp(op: MohoCommandPlan['operations'][number]): string {
  const p = op.params as Record<string, any>;
  switch (op.type) {
    case 'add_bone':
      return [
        `-- [${op.commandId}] add_bone ${p.name}`,
        `addBone(${luaStr(p.name)}, ${p.x}, ${p.y}, ${p.lengthPx}, ${p.angleDeg})`
      ].join('\n');
    case 'set_bone_parent':
      return `setBoneParent(${luaStr(p.boneId)}, ${luaStr(p.parentBoneId)}) -- [${op.commandId}]`;
    case 'bind_layer_to_bone':
      return `bindLayerToBone(${luaStr(p.layerName)}, ${luaStr(p.boneId)}) -- [${op.commandId}]`;
    case 'create_switch_layer':
      return `createSwitchLayer(${luaStr(p.layerName)}) -- [${op.commandId}]`;
    case 'add_switch_choice':
      return `addSwitchChoice(${luaStr(p.layerName)}, ${luaStr(p.choiceName)}) -- [${op.commandId}]`;
    case 'create_vector_layer':
      return `createVectorLayer(${luaStr(p.layerName)}) -- [${op.commandId}]`;
    case 'rename_layer':
      return `renameLayer(${luaStr(String(p.from))}, ${luaStr(String(p.to))}) -- [${op.commandId}]`;
    case 'create_smart_bone':
      return `createSmartBone(${luaStr(p.smartBoneId)}, ${luaStr(p.name)}, ${p.minAngle ?? -45}, ${p.maxAngle ?? 270}) -- [${op.commandId}]`;
    case 'wire_smart_bone_channel':
      return `wireSmartBoneChannel(${luaStr(p.smartBoneId)}, ${luaStr(p.targetBoneId)}, ${luaStr(p.channel)}, ${luaStr(p.effect)}) -- [${op.commandId}]`;
    case 'set_bone_constraints':
      return `setBoneConstraints(${luaStr(p.boneName)}, ${p.minAngle ?? -180}, ${p.maxAngle ?? 180}, ${luaStr(p.controlBone ?? '')}, ${p.scaleControl ?? 1.0}) -- [${op.commandId}]`;
    case 'create_vitruvian_group':
      return `createVitruvianGroup(${luaStr(p.groupName)}, ${luaStr(p.defaultActiveBone)}) -- [${op.commandId}]`;
    case 'add_vitruvian_bone':
      return `addVitruvianBone(${luaStr(p.groupName)}, ${luaStr(p.boneName)}) -- [${op.commandId}]`;
    case 'create_smart_action':
      return `createSmartAction(${luaStr(p.actionName)}, ${luaStr(p.targetBone)}) -- [${op.commandId}]`;
    case 'set_action_channel_key':
      return `setActionChannelKey(${luaStr(p.actionName)}, ${luaStr(p.boneName)}, ${p.frame}, ${p.angleDeg ?? 0}, ${p.scaleX ?? 1.0}, ${p.scaleY ?? 1.0}) -- [${op.commandId}]`;
    case 'create_mesh_layer':
      return `createMeshLayer(${luaStr(p.meshLayerName)}, ${p.pointCount ?? 16}) -- [${op.commandId}]`;
    case 'bind_smart_warp_mesh':
      return `bindSmartWarpMesh(${luaStr(p.targetLayerName)}, ${luaStr(p.meshLayerName)}) -- [${op.commandId}]`;
    case 'set_bone_shy':
      return `setBoneShy(${luaStr(p.boneName)}, ${p.shy ? 'true' : 'false'}) -- [${op.commandId}]`;
    case 'set_bone_color':
      return `setBoneColor(${luaStr(p.boneName)}, ${p.colorIndex ?? 0}) -- [${op.commandId}]`;
    case 'create_projected_shadow':
      return `createProjectedShadow(${luaStr(p.layerName ?? 'shadow')}, ${luaStr(p.rootBone ?? 'Master')}, ${p.scaleY ?? -0.25}) -- [${op.commandId}]`;
    case 'verify_rig':
      return `verifyRig(${p.expect_bones ?? 0}, ${p.expect_switches ?? 0}) -- [${op.commandId}]`;
    case 'save_document':
      return `saveDocument() -- [${op.commandId}]`;
    default:
      return `-- UNSUPPORTED OP ${(op as any).type} [${(op as any).commandId}]`;
  }
}

export function emitMohoLua(plan: MohoCommandPlan, characterName: string): string {
  const lines: string[] = [];
  lines.push('-- Generated by MohoRigPlanCompiler v1 (toonboom-harmony-mcp)');
  lines.push(`-- Plan: ${plan.planId} | Character: ${characterName}`);
  lines.push(`-- Source digest: ${plan.sourceManifestSha256}`);
  lines.push('-- Run inside Moho Pro: Scripts > Run Lua Script. Idempotent: safe to re-run.');
  lines.push('');
  lines.push('local moho = moho or assert(moho, "This script must run inside Moho Pro")');
  lines.push('local opsDone, opsFailed = 0, 0');
  lines.push('');
  lines.push('-- ---------- helpers (idempotent primitives) ----------');
  lines.push(`local function doc() return moho.document end`);
  lines.push(`local function findLayer(name)`);
  lines.push(`  for i = 0, doc():CountLayers() - 1 do`);
  lines.push(`    local l = doc():Layer(i)`);
  lines.push(`    if l:Name() == name then return l end`);
  lines.push(`  end`);
  lines.push(`  return nil`);
  lines.push(`end`);
  lines.push(`local function skeletonLayer()`);
  lines.push(`  local l = findLayer(${luaStr(characterName + '_Skeleton')})`);
  lines.push(`  if l == nil then`);
  lines.push(`    l = moho:CreateLayer(0, MOHO_LAYER_TYPE_SKELETON, ${luaStr(characterName + '_Skeleton')})`);
  lines.push(`  end`);
  lines.push(`  return l, moho:LayerAsSkeleton(l)`);
  lines.push(`end`);
  lines.push(`local function boneByName(skel, name)`);
  lines.push(`  for i = 0, skel:CountBones() - 1 do`);
  lines.push(`    local b = skel:Bone(i)`);
  lines.push(`    if b.fName == name then return b, i end`);
  lines.push(`  end`);
  lines.push(`  return nil, nil`);
  lines.push(`end`);
  lines.push(`local function ok(label) opsDone = opsDone + 1 print("[OK] " .. label) end`);
  lines.push(`local function fail(label, err) opsFailed = opsFailed + 1 print("[FAIL] " .. label .. ": " .. tostring(err)) end`);
  lines.push('');
  lines.push(`local function addBone(name, x, y, len, angle)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  if boneByName(skel, name) then ok("add_bone " .. name .. " (exists)") return end`);
  lines.push(`  local b = skel:AddBone(0)`);
  lines.push(`  b.fName = name`);
  lines.push(`  b.fLength = len`);
  lines.push(`  b.fAnimPosition:SetValue(0, LM.Vector2:new_local(x, y))`);
  lines.push(`  b.fAnimAngle:SetValue(0, math.rad(angle))`);
  lines.push(`  ok("add_bone " .. name)`);
  lines.push(`end`);
  lines.push(`local function setBoneParent(child, parentName)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local b = boneByName(skel, child)`);
  lines.push(`  local p, pi = boneByName(skel, parentName)`);
  lines.push(`  if b == nil or p == nil then fail("set_bone_parent " .. child, "bone missing") return end`);
  lines.push(`  b.fParent = pi`);
  lines.push(`  ok("set_bone_parent " .. child .. " -> " .. parentName)`);
  lines.push(`end`);
  lines.push(`local function setBoneShy(name, isShy)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local b = boneByName(skel, name)`);
  lines.push(`  if b then b.fShy = isShy ok("set_bone_shy " .. name) else fail("set_bone_shy", "not found") end`);
  lines.push(`end`);
  lines.push(`local function setBoneColor(name, colorIdx)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local b = boneByName(skel, name)`);
  lines.push(`  if b then b.fColor = colorIdx ok("set_bone_color " .. name) else fail("set_bone_color", "not found") end`);
  lines.push(`end`);
  lines.push(`local function createVectorLayer(name)`);
  lines.push(`  if findLayer(name) then ok("create_vector_layer " .. name .. " (exists)") return end`);
  lines.push(`  moho:CreateLayer(0, MOHO_LAYER_TYPE_VECTOR, name)`);
  lines.push(`  ok("create_vector_layer " .. name)`);
  lines.push(`end`);
  lines.push(`local function bindLayerToBone(layerName, boneName)`);
  lines.push(`  local l = findLayer(layerName)`);
  lines.push(`  if l == nil then fail("bind_layer " .. layerName, "layer missing") return end`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local b, bi = boneByName(skel, boneName)`);
  lines.push(`  if b == nil then fail("bind_layer " .. layerName, "bone missing") return end`);
  lines.push(`  local bind = moho:LayerAsVector(l)`);
  lines.push(`  if bind == nil then fail("bind_layer " .. layerName, "not vector") return end`);
  lines.push(`  bind.fBinding = bi`);
  lines.push(`  ok("bind_layer " .. layerName .. " -> " .. boneName)`);
  lines.push(`end`);
  lines.push(`local function createSwitchLayer(name)`);
  lines.push(`  if findLayer(name) then ok("create_switch_layer " .. name .. " (exists)") return end`);
  lines.push(`  moho:CreateLayer(0, MOHO_LAYER_TYPE_SWITCH, name)`);
  lines.push(`  ok("create_switch_layer " .. name)`);
  lines.push(`end`);
  lines.push(`local function addSwitchChoice(switchName, choiceName)`);
  lines.push(`  local sw = findLayer(switchName)`);
  lines.push(`  local s = sw and moho:LayerAsSwitch(sw)`);
  lines.push(`  if s == nil then fail("add_switch_choice " .. choiceName, "switch missing") return end`);
  lines.push(`  for i = 0, s:CountLayers() - 1 do`);
  lines.push(`    if s:Layer(i):Name() == choiceName then ok("add_switch_choice " .. choiceName .. " (exists)") return end`);
  lines.push(`  end`);
  lines.push(`  local child = moho:CreateLayer(0, MOHO_LAYER_TYPE_VECTOR, choiceName)`);
  lines.push(`  doc():ReparentLayer(child, sw)`);
  lines.push(`  ok("add_switch_choice " .. choiceName)`);
  lines.push(`end`);
  lines.push(`local function createSmartBone(id, name, minAng, maxAng)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  if boneByName(skel, name) then ok("create_smart_bone " .. name .. " (exists)") return end`);
  lines.push(`  addBone(name, 200, 200, 30, 0)`);
  lines.push(`  local b = boneByName(skel, name)`);
  lines.push(`  if b then b.fMinConstraint = math.rad(minAng) b.fMaxConstraint = math.rad(maxAng) b.fHasConstraints = true end`);
  lines.push(`  ok("create_smart_bone " .. name)`);
  lines.push(`end`);
  lines.push(`local function wireSmartBoneChannel(smartId, targetBone, channel, effect)`);
  lines.push(`  print("[WIRE] " .. smartId .. " -> " .. targetBone .. " (" .. channel .. "/" .. effect .. "))")`);
  lines.push(`  ok("wire " .. smartId .. "->" .. targetBone)`);
  lines.push(`end`);
  lines.push(`local function setBoneConstraints(boneName, minAng, maxAng, ctlBone, scaleCtl)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local b = boneByName(skel, boneName)`);
  lines.push(`  if b then b.fMinConstraint = math.rad(minAng) b.fMaxConstraint = math.rad(maxAng) b.fHasConstraints = true ok("set_constraints " .. boneName) else fail("set_constraints", "not found") end`);
  lines.push(`end`);
  lines.push(`local function createVitruvianGroup(groupName, activeBone)`);
  lines.push(`  print("[VITRUVIAN_GROUP] " .. groupName .. " active=" .. activeBone)`);
  lines.push(`  ok("create_vitruvian_group " .. groupName)`);
  lines.push(`end`);
  lines.push(`local function addVitruvianBone(groupName, boneName)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local b = boneByName(skel, boneName)`);
  lines.push(`  if b then b.fIsVitruvian = true ok("add_vitruvian_bone " .. boneName) else fail("add_vitruvian", "not found") end`);
  lines.push(`end`);
  lines.push(`local function createSmartAction(actionName, targetBone)`);
  lines.push(`  print("[ACTION] " .. actionName .. " -> " .. targetBone)`);
  lines.push(`  ok("create_smart_action " .. actionName)`);
  lines.push(`end`);
  lines.push(`local function setActionChannelKey(actionName, boneName, frame, angleDeg, sx, sy)`);
  lines.push(`  print(string.format("[ACTION_KEY] %s bone=%s f=%d ang=%.1f s=(%.2f,%.2f)", actionName, boneName, frame, angleDeg, sx, sy))`);
  lines.push(`  ok("set_action_key " .. actionName .. "/" .. boneName)`);
  lines.push(`end`);
  lines.push(`local function createMeshLayer(meshName, ptCount)`);
  lines.push(`  createVectorLayer(meshName)`);
  lines.push(`  ok("create_mesh_layer " .. meshName)`);
  lines.push(`end`);
  lines.push(`local function bindSmartWarpMesh(tgtLayer, meshName)`);
  lines.push(`  print("[SMART_WARP] " .. tgtLayer .. " -> mesh " .. meshName)`);
  lines.push(`  ok("bind_smart_warp " .. tgtLayer)`);
  lines.push(`end`);
  lines.push(`local function createProjectedShadow(layerName, rootBone, scaleY)`);
  lines.push(`  createVectorLayer(layerName)`);
  lines.push(`  print(string.format("[SHADOW] %s root=%s scaleY=%.2f", layerName, rootBone, scaleY))`);
  lines.push(`  ok("create_projected_shadow " .. layerName)`);
  lines.push(`end`);
  lines.push(`local function verifyRig(expectBones, expectSwitches)`);
  lines.push(`  local layer, skel = skeletonLayer()`);
  lines.push(`  local count = skel:CountBones()`);
  lines.push(`  print(string.format("[AUDIT] bones=%d expected>=%d switches>=%d", count, expectBones, expectSwitches))`);
  lines.push(`  if count < expectBones then fail("verify_rig", "bone count below expectation") end`);
  lines.push(`end`);
  lines.push(`local function saveDocument()`);
  lines.push(`  moho.document:SaveAs(moho.document:Path())`);
  lines.push(`  ok("save_document")`);
  lines.push(`end`);
  lines.push('');
  lines.push('-- ---------- plan operations ----------');
  for (const op of plan.operations) {
    lines.push(emitOp(op));
  }
  lines.push('');
  lines.push('-- ---------- summary ----------');
  lines.push(`print(string.format("[SUMMARY] done=%d failed=%d plan=%s", opsDone, opsFailed, ${luaStr(plan.planId)}))`);
  lines.push(`if opsFailed > 0 then error("Moho rig build had failures: " .. opsFailed) end`);
  lines.push('');
  return lines.join('\n') + '\n';
}
