import { z } from 'zod';
export declare const ANIMATION_CRITIC_SCHEMA_VERSION = "1.0";
export declare const criticCheckTypeSchema: z.ZodEnum<["missing_drawings", "broken_exposures", "holes", "layer_order", "palette_inconsistency", "collisions", "detached_parts", "broken_pivots", "invalid_deformers", "excessive_keys", "unstable_contours", "frozen_motion", "lost_motion_events", "timing_mismatch", "pose_readability", "silhouette_clarity", "staging", "emotional_clarity", "gesture_motivation", "timing_quality", "spacing", "anticipation", "follow_through", "overacting", "underacting", "dead_motion", "mechanical_motion", "repetitive_gestures", "gaze_direction", "reaction_timing", "camera_motivation"]>;
export declare const criticCheckResultSchema: z.ZodObject<{
    checkType: z.ZodEnum<["missing_drawings", "broken_exposures", "holes", "layer_order", "palette_inconsistency", "collisions", "detached_parts", "broken_pivots", "invalid_deformers", "excessive_keys", "unstable_contours", "frozen_motion", "lost_motion_events", "timing_mismatch", "pose_readability", "silhouette_clarity", "staging", "emotional_clarity", "gesture_motivation", "timing_quality", "spacing", "anticipation", "follow_through", "overacting", "underacting", "dead_motion", "mechanical_motion", "repetitive_gestures", "gaze_direction", "reaction_timing", "camera_motivation"]>;
    passed: z.ZodBoolean;
    score: z.ZodNumber;
    severity: z.ZodEnum<["critical", "high", "medium", "low", "info"]>;
    affectedFrames: z.ZodDefault<z.ZodArray<z.ZodNumber, "many">>;
    affectedParts: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    evidence: z.ZodString;
    recommendation: z.ZodOptional<z.ZodString>;
    alternative: z.ZodOptional<z.ZodString>;
    confidence: z.ZodNumber;
    humanReviewRequired: z.ZodDefault<z.ZodBoolean>;
}, "strict", z.ZodTypeAny, {
    confidence: number;
    severity: "low" | "medium" | "high" | "critical" | "info";
    passed: boolean;
    evidence: string;
    score: number;
    checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
    affectedFrames: number[];
    affectedParts: string[];
    humanReviewRequired: boolean;
    recommendation?: string | undefined;
    alternative?: string | undefined;
}, {
    confidence: number;
    severity: "low" | "medium" | "high" | "critical" | "info";
    passed: boolean;
    evidence: string;
    score: number;
    checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
    recommendation?: string | undefined;
    affectedFrames?: number[] | undefined;
    affectedParts?: string[] | undefined;
    alternative?: string | undefined;
    humanReviewRequired?: boolean | undefined;
}>;
export declare const criticReportSchema: z.ZodObject<{
    reportId: z.ZodString;
    variantId: z.ZodString;
    sceneId: z.ZodString;
    timestamp: z.ZodString;
    technicalChecks: z.ZodArray<z.ZodObject<{
        checkType: z.ZodEnum<["missing_drawings", "broken_exposures", "holes", "layer_order", "palette_inconsistency", "collisions", "detached_parts", "broken_pivots", "invalid_deformers", "excessive_keys", "unstable_contours", "frozen_motion", "lost_motion_events", "timing_mismatch", "pose_readability", "silhouette_clarity", "staging", "emotional_clarity", "gesture_motivation", "timing_quality", "spacing", "anticipation", "follow_through", "overacting", "underacting", "dead_motion", "mechanical_motion", "repetitive_gestures", "gaze_direction", "reaction_timing", "camera_motivation"]>;
        passed: z.ZodBoolean;
        score: z.ZodNumber;
        severity: z.ZodEnum<["critical", "high", "medium", "low", "info"]>;
        affectedFrames: z.ZodDefault<z.ZodArray<z.ZodNumber, "many">>;
        affectedParts: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        evidence: z.ZodString;
        recommendation: z.ZodOptional<z.ZodString>;
        alternative: z.ZodOptional<z.ZodString>;
        confidence: z.ZodNumber;
        humanReviewRequired: z.ZodDefault<z.ZodBoolean>;
    }, "strict", z.ZodTypeAny, {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        affectedFrames: number[];
        affectedParts: string[];
        humanReviewRequired: boolean;
        recommendation?: string | undefined;
        alternative?: string | undefined;
    }, {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        recommendation?: string | undefined;
        affectedFrames?: number[] | undefined;
        affectedParts?: string[] | undefined;
        alternative?: string | undefined;
        humanReviewRequired?: boolean | undefined;
    }>, "many">;
    artisticChecks: z.ZodArray<z.ZodObject<{
        checkType: z.ZodEnum<["missing_drawings", "broken_exposures", "holes", "layer_order", "palette_inconsistency", "collisions", "detached_parts", "broken_pivots", "invalid_deformers", "excessive_keys", "unstable_contours", "frozen_motion", "lost_motion_events", "timing_mismatch", "pose_readability", "silhouette_clarity", "staging", "emotional_clarity", "gesture_motivation", "timing_quality", "spacing", "anticipation", "follow_through", "overacting", "underacting", "dead_motion", "mechanical_motion", "repetitive_gestures", "gaze_direction", "reaction_timing", "camera_motivation"]>;
        passed: z.ZodBoolean;
        score: z.ZodNumber;
        severity: z.ZodEnum<["critical", "high", "medium", "low", "info"]>;
        affectedFrames: z.ZodDefault<z.ZodArray<z.ZodNumber, "many">>;
        affectedParts: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        evidence: z.ZodString;
        recommendation: z.ZodOptional<z.ZodString>;
        alternative: z.ZodOptional<z.ZodString>;
        confidence: z.ZodNumber;
        humanReviewRequired: z.ZodDefault<z.ZodBoolean>;
    }, "strict", z.ZodTypeAny, {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        affectedFrames: number[];
        affectedParts: string[];
        humanReviewRequired: boolean;
        recommendation?: string | undefined;
        alternative?: string | undefined;
    }, {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        recommendation?: string | undefined;
        affectedFrames?: number[] | undefined;
        affectedParts?: string[] | undefined;
        alternative?: string | undefined;
        humanReviewRequired?: boolean | undefined;
    }>, "many">;
    overallScore: z.ZodNumber;
    technicalScore: z.ZodNumber;
    artisticScore: z.ZodNumber;
    passed: z.ZodBoolean;
    criticalIssues: z.ZodNumber;
    highIssues: z.ZodNumber;
    recommendations: z.ZodArray<z.ZodString, "many">;
    humanReviewRequired: z.ZodBoolean;
    provenance: z.ZodObject<{
        engine: z.ZodString;
        version: z.ZodString;
        method: z.ZodEnum<["rule_based", "ml_critic", "hybrid"]>;
    }, "strict", z.ZodTypeAny, {
        method: "hybrid" | "rule_based" | "ml_critic";
        version: string;
        engine: string;
    }, {
        method: "hybrid" | "rule_based" | "ml_critic";
        version: string;
        engine: string;
    }>;
}, "strict", z.ZodTypeAny, {
    provenance: {
        method: "hybrid" | "rule_based" | "ml_critic";
        version: string;
        engine: string;
    };
    timestamp: string;
    reportId: string;
    passed: boolean;
    sceneId: string;
    variantId: string;
    humanReviewRequired: boolean;
    technicalChecks: {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        affectedFrames: number[];
        affectedParts: string[];
        humanReviewRequired: boolean;
        recommendation?: string | undefined;
        alternative?: string | undefined;
    }[];
    artisticChecks: {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        affectedFrames: number[];
        affectedParts: string[];
        humanReviewRequired: boolean;
        recommendation?: string | undefined;
        alternative?: string | undefined;
    }[];
    overallScore: number;
    technicalScore: number;
    artisticScore: number;
    criticalIssues: number;
    highIssues: number;
    recommendations: string[];
}, {
    provenance: {
        method: "hybrid" | "rule_based" | "ml_critic";
        version: string;
        engine: string;
    };
    timestamp: string;
    reportId: string;
    passed: boolean;
    sceneId: string;
    variantId: string;
    humanReviewRequired: boolean;
    technicalChecks: {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        recommendation?: string | undefined;
        affectedFrames?: number[] | undefined;
        affectedParts?: string[] | undefined;
        alternative?: string | undefined;
        humanReviewRequired?: boolean | undefined;
    }[];
    artisticChecks: {
        confidence: number;
        severity: "low" | "medium" | "high" | "critical" | "info";
        passed: boolean;
        evidence: string;
        score: number;
        checkType: "staging" | "missing_drawings" | "broken_exposures" | "holes" | "layer_order" | "palette_inconsistency" | "collisions" | "detached_parts" | "broken_pivots" | "invalid_deformers" | "excessive_keys" | "unstable_contours" | "frozen_motion" | "lost_motion_events" | "timing_mismatch" | "pose_readability" | "silhouette_clarity" | "emotional_clarity" | "gesture_motivation" | "timing_quality" | "spacing" | "anticipation" | "follow_through" | "overacting" | "underacting" | "dead_motion" | "mechanical_motion" | "repetitive_gestures" | "gaze_direction" | "reaction_timing" | "camera_motivation";
        recommendation?: string | undefined;
        affectedFrames?: number[] | undefined;
        affectedParts?: string[] | undefined;
        alternative?: string | undefined;
        humanReviewRequired?: boolean | undefined;
    }[];
    overallScore: number;
    technicalScore: number;
    artisticScore: number;
    criticalIssues: number;
    highIssues: number;
    recommendations: string[];
}>;
export type CriticReport = z.infer<typeof criticReportSchema>;
export type CriticCheckResult = z.infer<typeof criticCheckResultSchema>;
export type CriticCheckType = z.infer<typeof criticCheckTypeSchema>;
