import { z } from 'zod';
export declare const ARTIST_CORRECTION_SCHEMA_VERSION = "1.0";
export declare const correctionScopeSchema: z.ZodEnum<["key_poses", "timing", "camera", "layer_structure", "palette", "representation", "full_scene"]>;
export declare const correctionTypeSchema: z.ZodEnum<["position", "rotation", "scale", "keyframe_timing", "keyframe_value", "exposure_change", "drawing_substitution", "deformer_adjustment", "palette_color", "camera_move", "representation_change", "structural"]>;
export declare const artistCorrectionSchema: z.ZodObject<{
    correctionId: z.ZodString;
    sceneId: z.ZodString;
    versionBefore: z.ZodString;
    versionAfter: z.ZodString;
    timestamp: z.ZodString;
    artistId: z.ZodOptional<z.ZodString>;
    scope: z.ZodEnum<["key_poses", "timing", "camera", "layer_structure", "palette", "representation", "full_scene"]>;
    type: z.ZodEnum<["position", "rotation", "scale", "keyframe_timing", "keyframe_value", "exposure_change", "drawing_substitution", "deformer_adjustment", "palette_color", "camera_move", "representation_change", "structural"]>;
    affectedParts: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    affectedFrames: z.ZodDefault<z.ZodArray<z.ZodNumber, "many">>;
    delta: z.ZodRecord<z.ZodString, z.ZodAny>;
    comment: z.ZodOptional<z.ZodString>;
    reason: z.ZodOptional<z.ZodString>;
    timeSpentMinutes: z.ZodOptional<z.ZodNumber>;
    accepted: z.ZodDefault<z.ZodBoolean>;
    previousCriticOutput: z.ZodOptional<z.ZodAny>;
    chosenRepresentation: z.ZodOptional<z.ZodString>;
}, "strict", z.ZodTypeAny, {
    type: "rotation" | "position" | "scale" | "camera_move" | "drawing_substitution" | "keyframe_timing" | "keyframe_value" | "exposure_change" | "deformer_adjustment" | "palette_color" | "representation_change" | "structural";
    timestamp: string;
    delta: Record<string, any>;
    sceneId: string;
    affectedFrames: number[];
    affectedParts: string[];
    correctionId: string;
    versionBefore: string;
    versionAfter: string;
    accepted: boolean;
    scope: "palette" | "timing" | "camera" | "representation" | "key_poses" | "layer_structure" | "full_scene";
    reason?: string | undefined;
    comment?: string | undefined;
    artistId?: string | undefined;
    timeSpentMinutes?: number | undefined;
    previousCriticOutput?: any;
    chosenRepresentation?: string | undefined;
}, {
    type: "rotation" | "position" | "scale" | "camera_move" | "drawing_substitution" | "keyframe_timing" | "keyframe_value" | "exposure_change" | "deformer_adjustment" | "palette_color" | "representation_change" | "structural";
    timestamp: string;
    delta: Record<string, any>;
    sceneId: string;
    correctionId: string;
    versionBefore: string;
    versionAfter: string;
    scope: "palette" | "timing" | "camera" | "representation" | "key_poses" | "layer_structure" | "full_scene";
    reason?: string | undefined;
    comment?: string | undefined;
    affectedFrames?: number[] | undefined;
    affectedParts?: string[] | undefined;
    accepted?: boolean | undefined;
    artistId?: string | undefined;
    timeSpentMinutes?: number | undefined;
    previousCriticOutput?: any;
    chosenRepresentation?: string | undefined;
}>;
export declare const artistCorrectionHistoryEntrySchema: z.ZodObject<{
    correctionId: z.ZodString;
    sceneId: z.ZodString;
    version: z.ZodString;
    timestamp: z.ZodString;
    artistId: z.ZodOptional<z.ZodString>;
    summary: z.ZodString;
    accepted: z.ZodBoolean;
}, "strict", z.ZodTypeAny, {
    version: string;
    timestamp: string;
    summary: string;
    sceneId: string;
    correctionId: string;
    accepted: boolean;
    artistId?: string | undefined;
}, {
    version: string;
    timestamp: string;
    summary: string;
    sceneId: string;
    correctionId: string;
    accepted: boolean;
    artistId?: string | undefined;
}>;
export declare const trainingSampleSchema: z.ZodObject<{
    sampleId: z.ZodString;
    sceneId: z.ZodString;
    version: z.ZodString;
    correctionId: z.ZodString;
    inputManifest: z.ZodAny;
    correctedManifest: z.ZodAny;
    correctionDelta: z.ZodRecord<z.ZodString, z.ZodAny>;
    artistComment: z.ZodOptional<z.ZodString>;
    criticReportBefore: z.ZodOptional<z.ZodAny>;
    criticReportAfter: z.ZodOptional<z.ZodAny>;
    scope: z.ZodEnum<["key_poses", "timing", "camera", "layer_structure", "palette", "representation", "full_scene"]>;
    representationBefore: z.ZodOptional<z.ZodString>;
    representationAfter: z.ZodOptional<z.ZodString>;
    qualityImprovement: z.ZodOptional<z.ZodObject<{
        technicalScoreDelta: z.ZodOptional<z.ZodNumber>;
        artisticScoreDelta: z.ZodOptional<z.ZodNumber>;
        overallScoreDelta: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        technicalScoreDelta?: number | undefined;
        artisticScoreDelta?: number | undefined;
        overallScoreDelta?: number | undefined;
    }, {
        technicalScoreDelta?: number | undefined;
        artisticScoreDelta?: number | undefined;
        overallScoreDelta?: number | undefined;
    }>>;
    privacyLevel: z.ZodDefault<z.ZodEnum<["public", "studio_only", "private"]>>;
    timestamp: z.ZodString;
}, "strict", z.ZodTypeAny, {
    version: string;
    timestamp: string;
    sceneId: string;
    correctionId: string;
    privacyLevel: "public" | "studio_only" | "private";
    scope: "palette" | "timing" | "camera" | "representation" | "key_poses" | "layer_structure" | "full_scene";
    sampleId: string;
    correctionDelta: Record<string, any>;
    inputManifest?: any;
    correctedManifest?: any;
    artistComment?: string | undefined;
    criticReportBefore?: any;
    criticReportAfter?: any;
    representationBefore?: string | undefined;
    representationAfter?: string | undefined;
    qualityImprovement?: {
        technicalScoreDelta?: number | undefined;
        artisticScoreDelta?: number | undefined;
        overallScoreDelta?: number | undefined;
    } | undefined;
}, {
    version: string;
    timestamp: string;
    sceneId: string;
    correctionId: string;
    scope: "palette" | "timing" | "camera" | "representation" | "key_poses" | "layer_structure" | "full_scene";
    sampleId: string;
    correctionDelta: Record<string, any>;
    privacyLevel?: "public" | "studio_only" | "private" | undefined;
    inputManifest?: any;
    correctedManifest?: any;
    artistComment?: string | undefined;
    criticReportBefore?: any;
    criticReportAfter?: any;
    representationBefore?: string | undefined;
    representationAfter?: string | undefined;
    qualityImprovement?: {
        technicalScoreDelta?: number | undefined;
        artisticScoreDelta?: number | undefined;
        overallScoreDelta?: number | undefined;
    } | undefined;
}>;
export declare const pairwisePreferenceSchema: z.ZodObject<{
    preferenceId: z.ZodString;
    sceneId: z.ZodString;
    versionA: z.ZodString;
    versionB: z.ZodString;
    preferredVersion: z.ZodString;
    artistId: z.ZodOptional<z.ZodString>;
    reason: z.ZodOptional<z.ZodString>;
    criteria: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    confidence: z.ZodDefault<z.ZodNumber>;
    timestamp: z.ZodString;
}, "strict", z.ZodTypeAny, {
    confidence: number;
    timestamp: string;
    sceneId: string;
    preferenceId: string;
    versionA: string;
    versionB: string;
    preferredVersion: string;
    criteria: string[];
    reason?: string | undefined;
    artistId?: string | undefined;
}, {
    timestamp: string;
    sceneId: string;
    preferenceId: string;
    versionA: string;
    versionB: string;
    preferredVersion: string;
    confidence?: number | undefined;
    reason?: string | undefined;
    artistId?: string | undefined;
    criteria?: string[] | undefined;
}>;
export declare const datasetExportSchema: z.ZodObject<{
    exportId: z.ZodString;
    sceneIds: z.ZodArray<z.ZodString, "many">;
    format: z.ZodDefault<z.ZodEnum<["jsonl", "json", "parquet"]>>;
    includeCorrections: z.ZodDefault<z.ZodBoolean>;
    includePreferences: z.ZodDefault<z.ZodBoolean>;
    includeCriticReports: z.ZodDefault<z.ZodBoolean>;
    privacyLevel: z.ZodDefault<z.ZodEnum<["public", "studio_only", "private"]>>;
    outputPath: z.ZodString;
    timestamp: z.ZodString;
}, "strict", z.ZodTypeAny, {
    timestamp: string;
    outputPath: string;
    format: "json" | "jsonl" | "parquet";
    privacyLevel: "public" | "studio_only" | "private";
    exportId: string;
    sceneIds: string[];
    includeCorrections: boolean;
    includePreferences: boolean;
    includeCriticReports: boolean;
}, {
    timestamp: string;
    outputPath: string;
    exportId: string;
    sceneIds: string[];
    format?: "json" | "jsonl" | "parquet" | undefined;
    privacyLevel?: "public" | "studio_only" | "private" | undefined;
    includeCorrections?: boolean | undefined;
    includePreferences?: boolean | undefined;
    includeCriticReports?: boolean | undefined;
}>;
export type ArtistCorrection = z.infer<typeof artistCorrectionSchema>;
export type ArtistCorrectionHistoryEntry = z.infer<typeof artistCorrectionHistoryEntrySchema>;
export type TrainingSample = z.infer<typeof trainingSampleSchema>;
export type PairwisePreference = z.infer<typeof pairwisePreferenceSchema>;
export type DatasetExport = z.infer<typeof datasetExportSchema>;
