import { z } from 'zod';
export type EngineMode = 'simulation' | 'dry_run' | 'real' | 'hybrid' | 'moonshot';
export type ExecutionStatus = 'success' | 'partial_success' | 'simulation_success' | 'unsupported' | 'blocked' | 'failed' | 'requires_human';
export interface StandardExecutionResult {
    mode: EngineMode;
    status: ExecutionStatus;
    isRealHarmonyExecution: boolean;
    simulated: boolean;
    placeholder: boolean;
    requiresHumanReview: boolean;
    requiresRealHarmony: boolean;
    warnings: string[];
    errors: string[];
    artifacts: string[];
    executionReportPath: string;
    correlationId: string;
    startedAt: string;
    completedAt: string;
    details?: Record<string, any>;
}
export declare const standardExecutionResultSchema: z.ZodObject<{
    mode: z.ZodEnum<["simulation", "dry_run", "real", "hybrid", "moonshot"]>;
    status: z.ZodEnum<["success", "partial_success", "simulation_success", "unsupported", "blocked", "failed", "requires_human"]>;
    isRealHarmonyExecution: z.ZodBoolean;
    simulated: z.ZodBoolean;
    placeholder: z.ZodBoolean;
    requiresHumanReview: z.ZodBoolean;
    requiresRealHarmony: z.ZodBoolean;
    warnings: z.ZodArray<z.ZodString, "many">;
    errors: z.ZodArray<z.ZodString, "many">;
    artifacts: z.ZodArray<z.ZodString, "many">;
    executionReportPath: z.ZodString;
    correlationId: z.ZodString;
    startedAt: z.ZodString;
    completedAt: z.ZodString;
    details: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    status: "failed" | "success" | "unsupported" | "blocked" | "partial_success" | "requires_human" | "simulation_success";
    mode: "real" | "simulation" | "hybrid" | "moonshot" | "dry_run";
    warnings: string[];
    requiresRealHarmony: boolean;
    requiresHumanReview: boolean;
    errors: string[];
    placeholder: boolean;
    simulated: boolean;
    isRealHarmonyExecution: boolean;
    artifacts: string[];
    executionReportPath: string;
    correlationId: string;
    startedAt: string;
    completedAt: string;
    details?: Record<string, any> | undefined;
}, {
    status: "failed" | "success" | "unsupported" | "blocked" | "partial_success" | "requires_human" | "simulation_success";
    mode: "real" | "simulation" | "hybrid" | "moonshot" | "dry_run";
    warnings: string[];
    requiresRealHarmony: boolean;
    requiresHumanReview: boolean;
    errors: string[];
    placeholder: boolean;
    simulated: boolean;
    isRealHarmonyExecution: boolean;
    artifacts: string[];
    executionReportPath: string;
    correlationId: string;
    startedAt: string;
    completedAt: string;
    details?: Record<string, any> | undefined;
}>;
export declare function createStandardExecutionResult(params: {
    mode?: EngineMode;
    status?: ExecutionStatus;
    isRealHarmonyExecution?: boolean;
    simulated?: boolean;
    placeholder?: boolean;
    requiresHumanReview?: boolean;
    requiresRealHarmony?: boolean;
    warnings?: string[];
    errors?: string[];
    artifacts?: string[];
    executionReportPath?: string;
    correlationId?: string;
    startedAt?: string;
    details?: Record<string, any>;
}): StandardExecutionResult;
