import crypto from 'crypto';import fs from 'fs';import path from 'path';
import {HarmonySceneCompiler} from '../harmonySceneCompiler.js';import {reconstructionManifestSchema,type HarmonyReconstructionManifest} from '../../schemas/reconstruction.js';import {harmonyCommandPlanV4Schema,type HarmonyCommandPlanV4} from '../../schemas/harmonyCommandPlanV4.js';import {verifyPathAccess} from '../../security.js';

export class HarmonyCommandPlanV4Compiler{
 compile(raw:unknown,source='reconstruction_manifest'):HarmonyCommandPlanV4{const manifest=reconstructionManifestSchema.parse(raw),legacy=new HarmonySceneCompiler().generateCommandPlan(manifest),manifestJson=JSON.stringify(manifest),sha=hash(manifestJson),commands:any[]=[];let n=1;const push=(type:string,params:any,preconditions:string[],level:'none'|'reversible'|'destructive',rollback:'none'|'delete_created'|'restore_snapshot'|'reopen_snapshot',kind:string,acceptance:string[])=>commands.push({commandId:`cmd_${String(n++).padStart(4,'0')}`,type,params,preconditions,destructiveLevel:level,idempotencyKey:hash(`${manifest.manifestId}:${type}:${JSON.stringify(params)}`).slice(0,32),rollback:{strategy:rollback,snapshotRequired:rollback==='restore_snapshot'||rollback==='reopen_snapshot'},expectedArtifact:{kind,path:null,nonempty:kind!=='state'},verification:{method:`inspect_${kind}`,required:true,acceptance}});
 push('snapshot_project',{label:`before_${manifest.manifestId}`},['project_open','project_saved'], 'none','none','snapshot',['snapshot_exists','snapshot_checksum_recorded']);
 for(const c of legacy.commands){if(c.type==='save_project')continue;push(c.type,c.params,['snapshot_exists'],'reversible','restore_snapshot',artifactKind(c.type),acceptanceFor(c.type));}
 if(!legacy.commands.some(c=>c.type==='create_peg')){const node=manifest.elements[0].nodeName;push('create_peg',{pegName:`${manifest.scene.name}_ROOT_PEG`,targetNodeName:node},['drawing_node_exists'],'reversible','restore_snapshot','peg',['peg_exists']);push('attach_drawing_to_peg',{pegName:`${manifest.scene.name}_ROOT_PEG`,drawingNodeName:node},['peg_exists','drawing_node_exists'],'reversible','restore_snapshot','peg',['peg_connected']);push('set_peg_pivot',{pegName:`${manifest.scene.name}_ROOT_PEG`,pivotX:0,pivotY:0},['peg_exists'],'reversible','restore_snapshot','peg',['pivot_persists']);push('set_transform_keyframe',{pegName:`${manifest.scene.name}_ROOT_PEG`,frame:1,positionX:0,positionY:0,rotation:0,scaleX:1,scaleY:1,skew:0},['peg_exists'],'reversible','restore_snapshot','peg',['keyframe_persists']);}
 push('save_project',{frameCount:manifest.source.frameCount,fps:manifest.scene.fps},['native_entities_created'],'reversible','restore_snapshot','xstage',['save_returned','xstage_nonempty']);
 push('close_project',{},['project_saved'],'none','reopen_snapshot','state',['session_closed']);
 push('reopen_project',{},['session_closed','xstage_nonempty'],'none','reopen_snapshot','state',['opened_from_disk']);
 push('inspect_native_entities',{expectedDrawings:manifest.drawings.length,expectedExposureFrames:manifest.source.frameCount,expectedPaletteColors:manifest.palettes[0].colors.length},['opened_from_disk'],'none','none','native_audit',['vector_type_tvg','drawings_nonempty','exposures_match','palette_linked','peg_persists']);
 push('render_preview',{startFrame:1,endFrame:Math.min(3,manifest.source.frameCount)},['native_audit_passed'],'none','none','png_sequence',['png_signature','frame_count_matches']);
 push('compare_render',{sourceManifestId:manifest.manifestId},['preview_nonempty'],'none','none','comparison_report',['images_readable','sizes_match']);
 push('rollback_snapshot',{label:`before_${manifest.manifestId}`},['comparison_complete'],'destructive','restore_snapshot','xstage',['snapshot_restored']);
 push('verify_rollback',{},['snapshot_restored'],'none','none','rollback_audit',['created_entities_absent','project_reopens']);
 const plan:any={schemaVersion:'4.0',planId:`hcv4_${hash(JSON.stringify(commands)).slice(0,24)}`,manifestId:manifest.manifestId,createdAt:new Date().toISOString(),status:'implemented_unverified',requiresRealHarmony:true,sourceManifestSha256:sha,commands,acceptanceGates:['native_tvg_round_trip','palette_round_trip','exposures_round_trip','peg_keys_round_trip','save_close_reopen','real_render','render_comparison','rollback_round_trip'],provenance:{compiler:'HarmonyCommandPlanV4Compiler v1',source}};return harmonyCommandPlanV4Schema.parse(plan);}
 verifyOffline(plan:HarmonyCommandPlanV4){const parsed=harmonyCommandPlanV4Schema.parse(plan),types=parsed.commands.map(c=>c.type),errors:string[]=[];for(const required of ['snapshot_project','create_palette','create_drawing_element','create_drawing','write_path','set_exposure','save_project','close_project','reopen_project','inspect_native_entities','render_preview','compare_render','rollback_snapshot','verify_rollback'])if(!types.includes(required as any))errors.push(`missing:${required}`);if(types.indexOf('snapshot_project')!==0)errors.push('snapshot_not_first');if(types.indexOf('reopen_project')<types.indexOf('close_project'))errors.push('reopen_before_close');if(types.indexOf('rollback_snapshot')<types.indexOf('compare_render'))errors.push('rollback_before_compare');const keys=new Set(parsed.commands.map(c=>c.idempotencyKey));if(keys.size!==parsed.commands.length)errors.push('duplicate_idempotency_key');return{status:errors.length?'failed':'implemented_unverified',executed:true,verified:errors.length===0,artifactCreated:false,requiresRealHarmony:true,errors,checks:{commandCount:parsed.commands.length,uniqueIdempotencyKeys:keys.size,acceptanceGateCount:parsed.acceptanceGates.length,offlineContractValid:errors.length===0},warnings:['Offline verification cannot prove TVG, save/reopen, render or rollback.']};}
 exportBundle(plan:HarmonyCommandPlanV4,manifest:unknown,directory:string){const parsed=reconstructionManifestSchema.parse(manifest),dir=verifyPathAccess(directory);fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});const files:{name:string;sha256:string;size:number}[]=[];const write=(name:string,data:string)=>{const p=path.join(dir,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);files.push({name,sha256:hash(data),size:Buffer.byteLength(data)});};const copy=(source:string,name:string)=>{const data=fs.readFileSync(source),p=path.join(dir,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);files.push({name,sha256:crypto.createHash('sha256').update(data).digest('hex'),size:data.length});};write('manifest.json',JSON.stringify(parsed,null,2));write('harmony_command_plan_v4.json',JSON.stringify(plan,null,2));const sourceMap:Record<string,string|null>={};for(const drawing of parsed.drawings){if(fs.existsSync(drawing.normalizedImagePath)){const name=`source_frames/${drawing.id}.png`;copy(drawing.normalizedImagePath,name);sourceMap[drawing.id]=name;}else sourceMap[drawing.id]=null;}write('source_frame_map.json',JSON.stringify(sourceMap,null,2));const bridge=path.resolve('scripts/python/harmony_bridge.py'),runner=path.resolve('scripts/python/harmony_phase2_runner.py');if(fs.existsSync(bridge))copy(bridge,'harmony_bridge.py');if(fs.existsSync(runner))copy(runner,'harmony_phase2_runner.py');write('RUN_ON_HARMONY_MACHINE.md',runnerInstructions());fs.writeFileSync(path.join(dir,'inventory.json'),JSON.stringify({status:'implemented_unverified',requiresRealHarmony:true,files},null,2));return{status:'implemented_unverified',executed:true,verified:true,artifactCreated:true,bundlePath:dir,files,warnings:['Native acceptance must run on licensed Harmony.',...Object.values(sourceMap).some(v=>v===null)?['Some source frames were unavailable and render comparison will fail closed.']:[]]};}
}
function hash(v:string){return crypto.createHash('sha256').update(v).digest('hex');}function artifactKind(t:string){if(t.includes('palette'))return'palette';if(t.includes('drawing')||t==='write_path')return'tvg';if(t.includes('exposure'))return'exposure';if(t.includes('peg')||t.includes('transform'))return'peg';if(t.includes('node')||t==='connect_nodes')return'node_graph';return t==='save_project'?'xstage':'state';}function acceptanceFor(t:string){const k=artifactKind(t);return k==='tvg'?['drawing_exists','vector_geometry_nonempty']:k==='exposure'?['timing_matches_manifest']:k==='palette'?['colour_id_persists']:k==='peg'?['node_and_keys_persist']:['operation_confirmed'];}function runnerInstructions(){return`# Phase 2 licensed Harmony runner\n\nThis package is not proof by itself.\n\nValidate offline:\n\n\`python harmony_phase2_runner.py --bundle . --validate-only\`\n\nRun on a licensed Harmony machine:\n\n\`python harmony_phase2_runner.py --bundle . --source-project /path/scene.xstage --work-dir /safe/work --python-packages /path/to/Harmony/python-packages\`\n\nThe runner reports verified_real only after apply/save, a fresh-process reopen audit, real render, snapshot restore and restored-project reopen.\n`;}
