import fs from 'fs';
import path from 'path';
import { EpisodeIR } from '../../schemas/countryballs/episodeIR.js';
import { CountryballsSeriesBible } from '../../schemas/countryballs/seriesBible.js';
import { CountryballsPhysicsSolver } from '../acting/physicsSolver.js';

export interface AnimateCompilationResult {
  jsflScript: string;
  outputPathFla: string;
  totalKeyframesGenerated: number;
  totalLayersCreated: number;
  symbolsCreated: string[];
}

export class AnimateCountryballsCompiler {
  private bible: CountryballsSeriesBible;

  constructor(bible: CountryballsSeriesBible) {
    this.bible = bible;
  }

  /**
   * Compiles an Episode IR into an automated Adobe Animate JSFL production script.
   */
  public compileToJsfl(episode: EpisodeIR, outputDir: string): AnimateCompilationResult {
    const flaFileName = `${episode.episodeId}.fla`;
    const outputPathFla = path.join(outputDir, flaFileName);
    const symbolsCreated: string[] = [];
    let totalKeyframes = 0;
    let totalLayers = 0;

    let jsfl = `// ==========================================================================\n`;
    jsfl += `// Adobe Animate Batch Compiler — Episode: ${episode.title} (${episode.episodeId})\n`;
    jsfl += `// Generated by Countryballs AI Studio OS Compiler\n`;
    jsfl += `// ==========================================================================\n\n`;

    // Step 1: Create Document
    jsfl += `var doc = fl.createDocument('timeline');\n`;
    jsfl += `if (!doc) { doc = fl.getDocumentDOM(); }\n`;
    jsfl += `doc.width = ${episode.canvas.width};\n`;
    jsfl += `doc.height = ${episode.canvas.height};\n`;
    jsfl += `doc.frameRate = ${episode.fps};\n`;
    jsfl += `doc.backgroundColor = '#1E1E24';\n\n`;

    // Step 2: Create Symbol Library
    jsfl += `// --- Symbol Library Generation ---\n`;
    jsfl += `var library = doc.library;\n\n`;

    // Base Countryball Symbols
    for (const charId of episode.characters) {
      const charDef = this.bible.characters[charId];
      if (!charDef) continue;

      const bodySymbol = `Char_${charId}_Body`;
      const eyesSymbol = `Char_${charId}_Eyes`;
      symbolsCreated.push(bodySymbol, eyesSymbol);

      jsfl += `library.addNewItem('movie clip', '${bodySymbol}');\n`;
      jsfl += `library.editItem('${bodySymbol}');\n`;
      jsfl += `doc.getTimeline().addNewLayer('Flag');\n`;
      jsfl += `doc.addNewOval({left: -${charDef.physical.radius}, top: -${charDef.physical.radius}, right: ${charDef.physical.radius}, bottom: ${charDef.physical.radius}});\n`;
      jsfl += `library.editItem(); // exit symbol edit\n\n`;

      // Eye Symbol (14 states)
      jsfl += `library.addNewItem('movie clip', '${eyesSymbol}');\n`;
      jsfl += `library.editItem('${eyesSymbol}');\n`;
      jsfl += `doc.getTimeline().addNewLayer('Eyes');\n`;
      for (let stateIdx = 1; stateIdx <= 14; stateIdx++) {
        if (stateIdx > 1) {
          jsfl += `doc.getTimeline().insertKeyframe(${stateIdx - 1});\n`;
        }
        jsfl += `doc.addNewOval({left: -20, top: -15, right: -5, bottom: 15});\n`;
        jsfl += `doc.addNewOval({left: 5, top: -15, right: 20, bottom: 15});\n`;
      }
      jsfl += `library.editItem(); // exit symbol edit\n\n`;

      // Accessories
      for (const acc of charDef.accessories) {
        symbolsCreated.push(acc.symbolName);
        jsfl += `library.addNewItem('graphic', '${acc.symbolName}');\n`;
        jsfl += `library.editItem('${acc.symbolName}');\n`;
        jsfl += `doc.addNewRectangle({left: -25, top: -25, right: 25, bottom: 25});\n`;
        jsfl += `library.editItem();\n\n`;
      }
    }

    // Step 3: Main Timeline Setup
    jsfl += `// --- Main Timeline Layers & Keyframes ---\n`;
    jsfl += `var timeline = doc.getTimeline();\n`;

    // Standard Layers
    const layers = [
      'Camera',
      'Overlay_Vignette',
      'Audio_Voice',
      'Audio_SFX',
      'Audio_Music',
      ...episode.characters.map(c => `Actor_${c}`),
      'Background'
    ];
    totalLayers = layers.length;

    layers.forEach((layerName, lIdx) => {
      if (lIdx === 0) {
        jsfl += `timeline.layers[0].name = '${layerName}';\n`;
      } else {
        jsfl += `timeline.addNewLayer('${layerName}');\n`;
      }
    });

    // Step 4: Scene & Shot Keyframe Baking
    let globalFrameCursor = 0;

    for (const scene of episode.scenes) {
      for (const shot of scene.shots) {
        const shotStartFrame = globalFrameCursor;
        const shotEndFrame = globalFrameCursor + shot.durationFrames;

        jsfl += `\n// Scene: ${scene.sceneId} | Shot: ${shot.shotId} (Frames ${shotStartFrame} -> ${shotEndFrame})\n`;

        // Actors animation
        for (const actorOnStage of shot.actorsOnStage) {
          const charDef = this.bible.characters[actorOnStage.actorId];
          if (!charDef) continue;

          const layerIndex = layers.indexOf(`Actor_${actorOnStage.actorId}`);
          if (layerIndex === -1) continue;

          jsfl += `timeline.currentLayer = ${layerIndex};\n`;
          jsfl += `timeline.setSelectedLayers(${layerIndex});\n`;

          if (shotStartFrame > 0) {
            jsfl += `timeline.insertKeyframe(${shotStartFrame});\n`;
            totalKeyframes++;
          }

          // Initial placement
          jsfl += `doc.addItem({x: 0, y: 0}, library.findItem('Char_${actorOnStage.actorId}_Body'));\n`;
          jsfl += `doc.setElementProperty('x', ${actorOnStage.x});\n`;
          jsfl += `doc.setElementProperty('y', ${actorOnStage.y});\n`;
          jsfl += `doc.setElementProperty('scaleX', ${actorOnStage.scale});\n`;
          jsfl += `doc.setElementProperty('scaleY', ${actorOnStage.scale});\n`;

          // Process timeline events for this actor in this shot
          const actorEvents = shot.events.filter(e => e.actor === actorOnStage.actorId);

          for (const evt of actorEvents) {
            if (evt.action) {
              const poses = CountryballsPhysicsSolver.solveActionCurves(
                evt.action.type,
                evt.frame,
                evt.action.durationFrames,
                charDef,
                evt.action.intensity
              );

              for (const pose of poses) {
                const targetF = shotStartFrame + pose.frame;
                if (targetF >= shotEndFrame) break;

                jsfl += `timeline.insertKeyframe(${targetF});\n`;
                jsfl += `doc.setElementProperty('x', ${(actorOnStage.x + pose.deltaX).toFixed(1)});\n`;
                jsfl += `doc.setElementProperty('y', ${(actorOnStage.y + pose.deltaY).toFixed(1)});\n`;
                jsfl += `doc.setElementProperty('scaleX', ${(actorOnStage.scale * pose.scaleX).toFixed(3)});\n`;
                jsfl += `doc.setElementProperty('scaleY', ${(actorOnStage.scale * pose.scaleY).toFixed(3)});\n`;
                jsfl += `doc.setElementProperty('rotation', ${pose.rotationDeg.toFixed(1)});\n`;
                totalKeyframes++;
              }
            }

            if (evt.hold) {
              const holdF = shotStartFrame + evt.frame;
              jsfl += `timeline.insertKeyframe(${holdF}); // Hold start: ${evt.hold.reason || 'comedic hold'}\n`;
              totalKeyframes++;
            }
          }
        }

        globalFrameCursor = shotEndFrame;
      }
    }

    // Step 5: Save Project
    const sanitizedOutputUri = outputPathFla.replace(/\\/g, '/');
    jsfl += `\n// --- Save Project ---\n`;
    jsfl += `var fileUri = 'file:///${sanitizedOutputUri.replace(/^([a-zA-Z]):/, '$1|')}';\n`;
    jsfl += `doc.saveAs(fileUri);\n`;
    jsfl += `fl.trace('Countryballs Episode compiled successfully: ' + fileUri);\n`;

    return {
      jsflScript: jsfl,
      outputPathFla,
      totalKeyframesGenerated: totalKeyframes,
      totalLayersCreated: totalLayers,
      symbolsCreated
    };
  }
}
