#!/usr/bin/env node
import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
import {SceneUnderstandingEngine} from '../dist/adapters/sceneUnderstanding/index.js';import {VoicePerformanceAnalyzer} from '../dist/adapters/voicePerformanceAnalyzer/index.js';import {PerformanceGenerator} from '../dist/adapters/performanceGenerator/index.js';import {VoicePerformanceReportBuilder} from '../dist/adapters/voicePerformanceReport/index.js';
const here=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(here,'..','output','ai_studio');fs.mkdirSync(out,{recursive:true});
function createWav(file){const rate=16000,dur=6,n=rate*dur,data=Buffer.alloc(n*2);for(let i=0;i<n;i++){const t=i/rate;const active=(t>.2&&t<1.8)||(t>2.1&&t<4)||(t>4.5&&t<5.8);const f=t<2?175:t<4.2?135:230;const amp=active?(.23+.13*Math.min(1,t/6)):0;data.writeInt16LE(Math.round(Math.sin(2*Math.PI*f*t)*amp*32767),i*2);}const b=Buffer.alloc(44+data.length);b.write('RIFF',0);b.writeUInt32LE(36+data.length,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(data.length,40);data.copy(b,44);fs.writeFileSync(file,b);}
const transcript='Ты всё знал? Я… ничего не знал. Не лги!',wav=path.join(out,'iteration2_demo_voice.wav');createWav(wav);
const scene=new SceneUnderstandingEngine().analyze({script:'Masha: Ты всё знал?\nIvan: Я… ничего не знал.\nMasha: Не лги!',sceneId:'iteration2_demo',sceneName:'Confrontation',fps:24,durationSeconds:6,characters:[{name:'Masha',role:'protagonist'},{name:'Ivan',role:'antagonist'}],dialogue:[{speaker:'Masha',text:'Ты всё знал?',startSec:.2,endSec:1.8},{speaker:'Ivan',text:'Я… ничего не знал.',startSec:2.1,endSec:4},{speaker:'Masha',text:'Не лги!',startSec:4.5,endSec:5.8}]});
const voice=new VoicePerformanceAnalyzer().analyze({audioPath:wav,transcript,speaker:'masha'}),set=new PerformanceGenerator().generateVariants(scene,voice,'masha',3),report=new VoicePerformanceReportBuilder().buildToFile(set,path.join(out,'iteration2_demo_report.html'));
console.log('AI ANIMATION STUDIO — ITERATION 2: VOICE & PERFORMANCE');console.log(`Audio: ${wav}`);console.log(`Words: ${voice.words.length}; pauses: ${voice.pauses.length}; energy samples: ${voice.loudness.length}; pitch samples: ${voice.pitchContour.length}`);for(const p of set.variants)console.log(`${p.style}: ${p.eventCount} events, confidence ${Math.round(p.confidence*100)}%`);console.log(`HTML report: ${report}`);console.log('STATUS: voiceAnalysis=true performanceVariants=true harmonyApplied=false');console.log('LIMIT: timing is CPU approximation; emotion is a proxy; output is a plan, not final animation.');
