import { z } from 'zod';
import fs from 'fs';
import { FactoryAuth, FactoryFoundationStore } from '../adapters/factoryFoundation/index.js';
import { ReconstructionClient } from '../adapters/reconstructionClient.js';
import { verifyPathAccess } from '../security.js';

const auth=z.object({authToken:z.string().optional()});const store=new FactoryFoundationStore(),security=new FactoryAuth(),worker=new ReconstructionClient();
export const factoryFoundationTools=[
 {name:'harmony.factory.system.status',description:'Фактический статус Phase 1 control plane.',inputSchema:auth,handler:async(a:any)=>{const p=security.authorize(a.authToken,'viewer');await store.initialize();return{status:p.authMode==='token'?'verified_real':'degraded',executed:true,verified:true,artifactCreated:false,warnings:p.authMode==='token'?[]:['Auth token не настроен: локальный dev mode.'],provenance:{jobBackend:'sqlite_dev',artifactStore:'content_addressed_local',principal:p},capabilities:{durableJobs:true,resume:true,cancel:true,registries:true,artifactIntegrity:true,heavyMlOutsideNode:true,postgres:false,redis:false,harmonyAvailable:false}};}},
 {name:'harmony.factory.project.create',description:'Создать durable factory job DAG.',inputSchema:auth.extend({type:z.string().default('scene'),input:z.record(z.any()).default({})}),handler:async(a:any)=>{security.authorize(a.authToken,'artist');return store.createJob(a.type,a.input,['validate_inputs','perception','retarget','preview','verify_artifacts']);}},
 {name:'harmony.factory.project.get_status',description:'Получить durable job и checkpoints.',inputSchema:auth.extend({jobId:z.string()}),handler:async(a:any)=>{security.authorize(a.authToken,'viewer');return store.getJob(a.jobId);}},
 {name:'harmony.factory.project.cancel',description:'Отменить durable job.',inputSchema:auth.extend({jobId:z.string()}),handler:async(a:any)=>{security.authorize(a.authToken,'director');return store.cancel(a.jobId);}},
 {name:'harmony.factory.registry.register',description:'Зарегистрировать model или dataset с checksum.',inputSchema:auth.extend({kind:z.enum(['model','dataset']),name:z.string(),revision:z.string(),checksum:z.string().regex(/^[a-fA-F0-9]{64}$/),status:z.enum(['available','disabled','unverified']),metadata:z.record(z.any()).default({})}),handler:async(a:any)=>{security.authorize(a.authToken,'pipeline_admin');return store.register(a.kind,a.name,a.revision,a.checksum,a.status,a.metadata);}},
 {name:'harmony.factory.registry.list',description:'Список model/dataset registry.',inputSchema:auth.extend({kind:z.enum(['model','dataset']).optional()}),handler:async(a:any)=>{security.authorize(a.authToken,'viewer');return store.listRegistry(a.kind);}},
 {name:'harmony.factory.assets.ingest',description:'Скопировать реальный файл в content-addressed store и проверить SHA-256.',inputSchema:auth.extend({sourcePath:z.string(),mediaType:z.string().default('application/octet-stream')}),handler:async(a:any)=>{security.authorize(a.authToken,'artist');return{status:'verified_real',executed:true,verified:true,artifactCreated:true,artifact:await store.ingest(a.sourcePath,a.mediaType),warnings:[],provenance:{store:'local_content_addressed'}};}},
 {name:'harmony.factory.run_scene',description:'Phase 1 vertical slice: real MP4+WAV через внешний Python worker → perception → retargeting → SVG preview.',inputSchema:auth.extend({videoPath:z.string(),audioPath:z.string(),outputDir:z.string()}),handler:async(a:any)=>{security.authorize(a.authToken,'artist');const videoPath=verifyPathAccess(a.videoPath),audioPath=verifyPathAccess(a.audioPath),outputDir=verifyPathAccess(a.outputDir);fs.mkdirSync(outputDir,{recursive:true});const job=await store.createJob('phase1_vertical',{videoPath,audioPath,outputDir},['validate_inputs','perception','retarget','preview','verify_artifacts']);const started=Date.now();try{await store.setJob(job.jobId,'running',.05);await store.setStep(job.jobId,'validate_inputs','completed',{videoSize:fs.statSync(videoPath).size,audioSize:fs.statSync(audioPath).size});const result=await worker.perceiveVideo({videoPath,audioPath,outputDir});for(const name of ['perception','retarget','preview','verify_artifacts'])await store.setStep(job.jobId,name,'completed',result);const artifacts=[];for(const file of [result.perceptionManifestPath,result.retargetingManifestPath,...result.previewFiles])artifacts.push(await store.ingest(file,file.endsWith('.svg')?'image/svg+xml':'application/json'));await store.setJob(job.jobId,'completed',1,{...result,artifacts});await store.metric('factory_scene_duration_ms',Date.now()-started,{jobId:job.jobId});return await store.getJob(job.jobId);}catch(error:any){await store.setJob(job.jobId,'failed',0,undefined,{message:error.message});throw error;}}}
];
